// <auto-generated />
using CijferRegistratie.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CijferRegistratie.Migrations
{
    [DbContext(typeof(CijferRegistratieDbContext))]
    [Migration("20230330182019_vakTabelEnDatabase")]
    partial class vakTabelEnDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CijferRegistratie.Data.Entities.Vak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EC")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vak");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EC = 4,
                            Naam = "Server"
                        },
                        new
                        {
                            Id = 2,
                            EC = 4,
                            Naam = "C#"
                        },
                        new
                        {
                            Id = 3,
                            EC = 3,
                            Naam = "Databases"
                        },
                        new
                        {
                            Id = 4,
                            EC = 3,
                            Naam = "UML"
                        },
                        new
                        {
                            Id = 5,
                            EC = 9,
                            Naam = "KBS"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
